# Generated by Django 4.2.2 on 2023-06-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Product',
        ),
    ]
