# Generated by Django 4.2.2 on 2023-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
