# Generated by Django 4.2.2 on 2023-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_contacts_description_contacts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, upload_to='work/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
