# Generated by Django 4.2.2 on 2023-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_worker_photo_worker_salary_worker_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
