# Generated by Django 4.2.2 on 2023-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_coffeeshop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shops/'),
        ),
    ]
