# Generated by Django 4.2.2 on 2023-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_coffeeshop_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Women'), ('T', 'Trans')], max_length=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
