# Generated by Django 4.2.2 on 2023-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='views',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
